### ISSUE TITLE
GM/Convert lib cannot found - windows7x64

### ISSUE THREAD

**Issue by hitaspdotnet** [pveller/adventureworks-moltin#3]
Hi master
I'm just start learning about eCommerce API's. I think your codes be awesome.
I have 3 days research about you and your notes and code's too.
Thanks for sharing. 
I have a issue with this git. "GM/Convert lib cannot found" 
I'm try Installing GM package with NPM and latest version .EXE GM Installer. 
Can you help me a little for "How i can use your Codes in Windows OS CMD?
best regards

**Comment by hitaspdotnet** [comment]
its done, my machine needed Restart & confirm upgrades!
But for Now, after processing images i have another issue 
`[ 'Slug must be unique']`
`..\node_modules\rx\dist\rx.js:77 throw e;`
what is this and how i can fix that
![image](https://user-images.githubusercontent.com/23167047/27536719-a49e59d6-5a85-11e7-8011-d8fb172b6e95.png)

**Comment by pveller** [comment]
`slug` is a unique identifier in Moltin. Since images were pre-processed correctly, the next thing the script would do is to import categories:

```
slug: row.name.toLowerCase()
```

are you sure you are importing into an empty Moltin store that has no data in it? If not, create a new store, make sure you don't create anything manually in it, and then re-run the script

**Comment by hitaspdotnet** [comment]
It's fixed. Thank you.
